### PR TITLE
Use actual newline character in Issue::buildXML().

### PR DESCRIPTION
**Pull request by bantu**
In PHP `'\n'` is a string of length two.

### CODE REVIEW

**Comment by kbsali** [comment]
Hi @bantu,

the unit tests don't pass.
Did you have a use case where this comparison was failing?

**Comment by bantu** [comment]
Oh, sorry. The test is broken too. There are no line breaks in the test on
line 113 (and the expected XML).

**Comment by kbsali** [comment]
could you update the test accordingly?

**Comment by bantu** [comment]
Yes. Done.

**Comment by kbsali** [comment]
thx

**Pull request merged**
