### PR TITLE
Added support for downloading attachments

### LINKED ISSUE #116: Not downloading attachment feature
As I had tested, you can download an attachment not only see the information about it.

If you want to download a file by the api you need to request by GET the resource but without the .json or .xml logging in with the header token auth (I tested it in that way).

Example: http://redmine.demo.com/attachments/{id}

### PR DESCRIPTION
**Pull request by gpilla**
Fixes #116

### CODE REVIEW

**Comment by kbsali** [comment]
excellent! Thanks @gpilla !

**Comment by gpilla** [comment]
Thanks you for merging so fast, now I dont need to change the project, just change the composer to dev.

**Comment by kbsali** [comment]
i'll bump the version soon!

**Comment by gpilla** [comment]
Can you tell me how soon?

Saludo Atte.

Gustavo Pilla.


2015-03-04 11:26 GMT-03:00 Kevin Saliou <notifications@github.com>:

**Comment by kbsali** [comment]
now!

**Comment by gpilla** [comment]
Thanks!

Saludo Atte.

Gustavo Pilla.


2015-03-05 5:50 GMT-03:00 Kevin Saliou <notifications@github.com>:

**Pull request merged**
