### PR TITLE
Release v2.5.0

### PR DESCRIPTION
**Pull request by Art4**
After merge of this PR we can tag and release `v2.5.0`.

### CODE REVIEW

**Comment by Art4** [comment]
@kbsali I would like to add the codecov badge on the README and need the Graphing token from Codecov.io. What do you think? Would you be so kind? You can find it in the settings: https://app.codecov.io/gh/kbsali/php-redmine-api/settings

**Review by kbsali — APPROVED** [review]
:+1:

**Comment by Art4** [comment]
@kbsali What do you think about the Graphing token from Codecov.io?

**Comment by kbsali** [comment]
sorry, did not see you messag :) -> `4P6dAaDbJ9`

**Review by kbsali — APPROVED** [review]
:+1:

**Comment by Art4** [comment]
I'm not sure why it's not working...

https://codecov.io/gh/kbsali/php-redmine-api/graph/badge.svg?token=4P6dAaDbJ9 shows "unknown" state.

with my account it is working fine: https://codecov.io/gh/Art4/php-redmine-api/graph/badge.svg?token=GRBNS1Q16N

**Comment by kbsali** [comment]
it should be fixed, i had to setup the branch it points to :)

**Pull request merged**
