### PR TITLE
Remove deprecated code

### PR DESCRIPTION
**Pull request by Art4**
This PR removes the deprecated `Redmine\Client`. Because this breaks backward compatibility it is the first step towards release v2.0 and refs https://github.com/kbsali/php-redmine-api/projects/3#card-57586454

I also reorder the tests a little bit and improved the MockClient for tests.

**Note:** Because this PR will be merged into `master` this branch will become the default branch for v2. For maintenance fixes in v1 I created a new branch `v1.x`. What do you think about renaming `master` to `v2.x` to precise the purpose of the branch?

### CODE REVIEW

**Review by kbsali — APPROVED** [review]
impressive! :muscle:

**Comment by Art4** [comment]
Thank you @kbsali.

What do think about the renaming the `master` branch to `v2.x` and make it the default branch?

**Comment by kbsali** [comment]
sure, that's a good idea.

**Comment by Art4** [comment]
It seems that I don't have enough rights to rename the default branch. Could you please do this?

**Comment by Art4** [comment]
> It seems that I don't have enough rights to rename the default branch. Could you please do this?

ping @kbsali

**Comment by kbsali** [comment]
oops, totally forgot this! :/
Sorry, I just created a new v2.x branch and made it the default one plus update the destination branch of this PR.
Do you think we can/should delete the master branch too?
It could be an issue for those who have set their dependency to `dev-master`...

**Comment by Art4** [comment]
No problem, no need for rush. :blush: 

I think deleting the `master` branch should be no problem. Using `dev-master` is highly discouraged as a dependency if one is not developing or using a specific feature branch. (See https://getcomposer.org/doc/articles/versions.md#branches)

If some libraries are using `dev-master` they will have breaking changes if we would merge this PR into master branch. If we keep the branch they will stop achieving updates. And if we delete the branch they will be forced to change their dependency to a recommended constraint like `^v1.8` or `^v2.0`.

So to push everyone to use a recommended way I would suggest to delete the `master` branch.

**Comment by kbsali** [comment]
you are right, I have deleted the master branch! :ok_hand:

**Pull request merged**
