### PR TITLE
Added a GuzzleClient for using this library with Guzzle

### PR DESCRIPTION
**Pull request by ferdynator**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #97 |
| License | MIT |

I have given the guzzle client a first try. Any comments or improvements are highly appreciated.

### CODE REVIEW

**Comment by kbsali** [comment]
sorry @ferdynator, haven't had time to review this yet, but i'm not forgetting you!
Impressive PR! Thanks a lot!
I'll try to take some time to review it this week! (especially the failing test).

Thanks again!

**Comment by ferdynator** [comment]
@kbsali Scrutinizer just timed out. Can you restart the tests? Take your time with the review and all. No need to rush it :)

**Comment by Art4** [comment]
This PR will break BC because of the renaming ``Client` to `CurlClient`. I would propose to add a `Client` extending `CurlClient`.



```php
<?php

namespace Redmine;

class Client extends CurlClient {}
```

**Comment by ferdynator** [comment]
Good point. I can do that if wanted.

**Comment by ferdynator** [comment]
How about I add the `Client` you suggest with a deprecation warning?

    trigger_error('The Client class is deprecated and will be removed in future versions. Use CurlClient or GuzzleClient instead', E_USER_DEPRECATED);

Also before merging I think some sort of documentation would be nice. I can write some myself but my English is not perfect and I have no experience with creating good documentations.

**Comment by Art4** [comment]
If these changes don't end up in a new major release (v2), I would recommend to follow [Semantic Versioning](http://semver.org/) and avoid backward incompatible API changes.

Maybe it's a cleaner solution to rename `CurlClient` back to `Client`...

**Comment by kbsali** [comment]
Sorry, not finding the right time to get around this... :|

@Art4 : i'm tagging this repo following semver, so that is not the issue i believe :)

@ferdynator i would indeed leave the curl client classname to be Client, that's too error prone (unless, as @Art4 suggests we make this a major release, but then again, make a major version release just for this seems exagerated). Ideally we should refactor a bit all this and make the Client class a wrapper of the real client class to be used, like the https://github.com/KnpLabs/php-github-api does : 

    // If you want the regular existing client
    $client = new Redmine\Client();

    // And if you want another driver you pass it as 
    $client = new Redmine\Client(
        new Redmine\GuzzleClient()
    );

    // Authenticate
    $client->authenticate('http://redmine.example.com', 'username', 'password');

The major change here is how the authentication is handled separately from the Client declaration.

What do you think @ferdynator & @Art4

**Comment by Art4** [comment]
I can't see a real benefit behind wrapping the `GuzzleClient` inside `Client`. Why not just leave it like it is and only provide `GuzzleClient` as a feature.

```php
// If you want the regular existing client
$client = new Redmine\Client('http://redmine.example.com', 'username', 'password');

// And if you want another driver just use it
$client = new Redmine\GuzzleClient('http://redmine.example.com', 'username', 'password');
```

This way @ferdynator only has to rename `CurlClient` back to `Client`.

**Comment by kbsali** [comment]
yep, that works for me. @ferdynator ?

**Comment by ferdynator** [comment]
I renamed the `CurlClient` back to `Client`. Is this fine with you? Also I merged the master branch back into mine but somehow Github says there are conflicts. How do I resolve them?

**Comment by kbsali** [comment]
@ferdynator thanks for the changes!
github gives you hints on how to fix conflicts

**Comment by ferdynator** [comment]
Was a little confusing. Also test coverage went down by 5%. Ill have a look at it as soon as I have some spare time.

**Comment by kbsali** [comment]
thanks @ferdynator and sorry for not merging your PR...
Maybe http://httplug.io/ would be a better option nowadays...?

**Comment by Art4** [comment]
I think it should be easy to build a `HttpClient` on base of this PR. This `HttpClient` will expect an optional Httplug-Adapter or will use internally the Guzzle6-Adapter, if no Adapter was set.

Example:

```php
// traditional workflow:
$client = new Redmine\Client('http://redmine.example.com', 'username', 'password');

// optional HttpClient with Guzzle inside as default
// (Redmine\HttpClient is technically a Httplug adapter, that needs a client)
// see http://docs.php-http.org/en/latest/clients.html
$client = new Redmine\HttpClient('http://redmine.example.com', 'username', 'password');

// or set your own HttpClient instead of Guzzle
//$curl_client = new Http\Client\Curl\Client($messageFactory, $streamFactory);
$client->setHttpClient($curl_client);
```

**Pull request closed without merging**
