### PR TITLE
Use uppercase in HTTP verbs

### PR DESCRIPTION
**Pull request by npotier**
This commit fixes the issue #278

### CODE REVIEW

**Comment by npotier** [comment]
Hi @kbsali i'm not sure to understand why the travis test fails... Do you have any clue ?

Thanks

**Comment by kbsali** [comment]
thanks @npotier , I think you'll have to update the unit tests too! :) The build is failing now! :)

**Comment by npotier** [comment]
Yes, I've seen that, but I don't understand why my modification make the tests fail...

I'll try to have a deeper look on it.

**Comment by kbsali** [comment]
@Art4 this PR is ready for merging, right?

**Review by Art4 — APPROVED** [review]
Hey @npotier Thanks for the PR. Everything looks fine. :+1:

Because this also affects v1 I tried to changed the base to the `v1.x` branch but messed up something with the Github UI. So I changed it back to the `v2.x` branch and will backport this PR into the `v1.x` branch.

@kbsali This can be merged.

**Comment by npotier** [comment]
Thanks @kbsali @Art4 and once again 👏 for your work

**Pull request merged**
