### PR TITLE
Update Project.php

### PR DESCRIPTION
**Pull request by urmaul**
listing() & getIdByName() fix in case there's more than 25 projects

### CODE REVIEW

**Comment by Art4** [comment]
This will only shift the problem. What are you going to do if you have more than 100 projects?

Rather than this PR I would recommend you this workaround:

````php
// This loads up to 100 projects in the client
$client->api('project')->all(['limit' => 100]);

// Now listing() returns more than 25 projects
$all_projects = $client->api('project')->listing();
```

**Comment by urmaul** [comment]
`Project->all()` is calling `retrieveAll()` method that gets all rows but only in case parameter 'limit' is passed so this really solves the problem.

**Comment by kbsali** [comment]
sorry for getting back so late on this PR @urmaul.
How about setting the default limit to 100 in retrieveAll() directly?

**Comment by kbsali** [comment]
closing for lack of activity

**Pull request closed without merging**
