### PR TITLE
Tidy up docblocks

### PR DESCRIPTION
**Pull request by jaymoulin**
Clean code dockblocks to ease autocompletion + understanding

### CODE REVIEW

**Comment by kbsali** [comment]
Thanks @jaymoulin for this thorough review! :+1: 
I'm not convinced however with the changes related to improve the auto-completion of the IDEs : the IDE requirements should not "affect" the code! How about adding a __call() method to the Client class, and add @\method to document this? (https://phpdoc.org/docs/latest/references/phpdoc/tags/method.html)
I believe this is supported by most of the IDEs! :)

**Comment by jaymoulin** [comment]
I don't get the point. Nothing here affects the code. As you can see, nothing changed in unit tests as well. It only corrects IDE interpretation because docblocks were not telling the truth! 
No BC break in this code and developpers can continue to code as they always did

**Comment by kbsali** [comment]
I know it is only comments and it is not affecting the code/functionality, but i'm really against adding extra comments/variables so IDE can auto-complete... specially given that the @\method/__call() solution i propose should solve the issue! :)

**Comment by jaymoulin** [comment]
Understood what you want. This will affect code but will be much cleaner. Also this PR will have to be a minor release instead of a bugfix one. I'll manage to handle that this week.

**Comment by kbsali** [comment]
we (you :) ) could also split it in 2 PRs! cs fix & IDE helper... up to you!

**Comment by kbsali** [comment]
thanks a lot, and sorry for being so fuzzy! ;)

**Comment by kbsali** [comment]
thanks @jaymoulin :+1:

**Pull request merged**
