### PR TITLE
Fix: allow multi-valued custom fields in issue creation

### PR DESCRIPTION
**Pull request by gggeek**

### CODE REVIEW

**Comment by kbsali** [comment]
@gggeek i believe @alxshr's PR #87 fixes exactly this,
but i unfortunately forgot about it! :|
I will merge it now, but i wanted to add some examples and tests.

**Comment by gggeek** [comment]
Indeed my PR seems to be a subset of the other one. I did not check thoroughly as it looked so much bigger I assumed it was something unrelated...

**Comment by kbsali** [comment]
:) it's been merged already, could you give it a shot and close your PR if appropriate?

Thanks!

**Comment by kbsali** [comment]
This PR duplicates #87

**Pull request closed without merging**
